name: gupshup_corner
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.4
  google_maps_flutter: ^2.1.6
  firebase_auth: ^3.3.19
  firebase_database: ^9.0.15
  firebase_core: ^1.17.1
  cloud_firestore: ^3.1.17
  bottom_bar: ^1.3.0+1
  get: ^4.6.1
  table_calendar: ^3.0.6
  google_fonts: ^3.0.1
  fluttertoast: ^8.0.9
  firebase_storage: ^10.2.17
  image_picker: ^0.8.5+3



  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/anims/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg





  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
